-- =====================================================================================
-- Serfira Core — V2: at-rest PII encryption for customers
-- -------------------------------------------------------------------------------------
-- Sprint 2 / PII hardening. Source of truth: 03_DOMAIN_MODEL.md §1.1, 04_GAPS_ADDENDUM.md §9,
-- ADR-004 (at-rest PII encryption).
--
-- Decisions encoded here:
--   1. `nik` and `phone` are stored as AES-256-GCM ciphertext written by an application-level
--      JPA AttributeConverter. The columns widen from VARCHAR(16)/VARCHAR(20) to TEXT because a
--      `v1:` ciphertext envelope does not fit in the original widths.
--   2. Uniqueness/lookup NEVER uses ciphertext. `nik_hash` (HMAC-SHA-256, unique) stays the NIK
--      key; a new `phone_lookup` column (HMAC-SHA-256 of the normalized phone) enforces the
--      "one phone per customer" business rule and is the phone search key. The HMAC/encryption
--      secrets live in application configuration, NEVER in the database.
--   3. `phone` becomes NOT NULL: it is the primary collection/reminder contact and the customer
--      form already treated it as required (frontend spec) — the nullable default in §1.1 was an
--      inconsistency, resolved per ADR-004.
--
-- Data note (MVP): no production/plaintext rows exist yet, so no backfill is needed. On a
-- database that already holds rows this migration fails loudly on purpose. V99__demo_seed.sql
-- (demo profile, Sprint 7) must create customers through the application so that ciphertext and
-- lookup values are generated by product code, NOT by raw SQL.
-- =====================================================================================

ALTER TABLE customer
    ALTER COLUMN nik   TYPE TEXT,
    ALTER COLUMN phone TYPE TEXT,
    ALTER COLUMN phone SET NOT NULL,
    ADD COLUMN phone_lookup CHAR(64) NOT NULL;

ALTER TABLE customer
    ADD CONSTRAINT uk_customer_phone_lookup UNIQUE (phone_lookup);