package com.serfira.shared.error;

/**
 * Machine-readable error codes from the standard envelope. Module-specific codes (payments, settlement, …)
 * extend this list as those modules are built.
 */
public enum ErrorCode {
	VALIDATION_ERROR,
	UNAUTHORIZED,
	NOT_FOUND,
	CONFLICT,
	CONCURRENT_MODIFICATION,
	FORBIDDEN,
	INTERNAL_ERROR,
	CONTRACT_NOT_FOUND,
	CONTRACT_STATE_INVALID,
	DUPLICATE_CONTRACT,
	PAYMENT_NOT_FOUND,
	INVALID_AS_OF_DATE,
	IDEMPOTENCY_KEY_EXPIRED,
	CREDIT_NOT_APPLICABLE,
	STALE_SETTLEMENT_QUOTE,
	SETTLEMENT_QUOTE_EXPIRED,
	SETTLEMENT_QUOTE_ALREADY_EXECUTED,
	CREDIT_EXCEEDS_SETTLEMENT
}